#!/bin/bash

# General Plots
# python3 plot_graph.py --game "Leduc Poker" --player o --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_o_C=16_LUCB_exploitability_log,data/bandit/final_exp_pull25k_L_poker_o_pullm_exploitability_log,data/MCCFR/L_poker_o_MCCFR_OS_exploitability_log,data/bandit/final_exp_L_poker_o_C=16_UCB_exploitability_log,data/onpath_flipping/final_exp_balanced_Lpoker_eps_constant=0.100000_oonpath_flipping_exploitability_log,data/onpath_flipping/final_exp_uniform_Lpoker_eps_constant=0.100000_oonpath_flipping_exploitability_log" --algorithms "IS-LUCB,Pull m,MCCFR OS (eps = 0.1),IS-UCB,On Path (balanced),On Path (uniform)" --yaxisupper 0.15
# python3 plot_graph.py --game "Leduc Poker" --player x --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_x_C=16_LUCB_exploitability_log,data/bandit/final_exp_pull25k_L_poker_x_pullm_exploitability_log,data/MCCFR/L_poker_x_MCCFR_OS_exploitability_log,data/bandit/final_exp_L_poker_x_C=16_UCB_exploitability_log,data/onpath_flipping/final_exp_balanced_Lpoker_eps_constant=0.100000_xonpath_flipping_exploitability_log,data/onpath_flipping/final_exp_uniform_Lpoker_eps_constant=0.100000_xonpath_flipping_exploitability_log" --algorithms "IS-LUCB,Pull m,MCCFR OS (eps = 0.1),IS-UCB, On Path (balanced),On Path (uniform)" --yaxisupper 0.15

# python3 plot_graph.py --game "Kuhn Poker" --player o --numexperiments 20 --numiterations 1000 --logfreq 10 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_K_poker_o_C=16_LUCB_exploitability_log,data/bandit/final_exp_pull250_K_poker_o_pullm_exploitability_log,data/MCCFR/K_poker_o_MCCFR_OS_exploitability_log,data/bandit/final_exp_K_poker_o_C=16_UCB_exploitability_log,data/onpath_flipping/final_exp_balanced_Kpoker_eps_constant=0.100000_oonpath_flipping_exploitability_log,data/onpath_flipping/final_exp_uniform_Kpoker_eps_constant=0.100000_oonpath_flipping_exploitability_log" --algorithms "IS-LUCB,Pull m,MCCFR OS (eps = 0.1),IS-UCB,On Path (balanced),On Path (uniform)" --yaxisupper 0.1
# python3 plot_graph.py --game "Kuhn Poker" --player x --numexperiments 20 --numiterations 1000 --logfreq 10 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_K_poker_x_C=16_LUCB_exploitability_log,data/bandit/final_exp_pull250_K_poker_x_pullm_exploitability_log,data/MCCFR/K_poker_x_MCCFR_OS_exploitability_log,data/bandit/final_exp_K_poker_x_C=16_UCB_exploitability_log,data/onpath_flipping/final_exp_balanced_Kpoker_eps_constant=0.100000_xonpath_flipping_exploitability_log,data/onpath_flipping/final_exp_uniform_Kpoker_eps_constant=0.100000_xonpath_flipping_exploitability_log" --algorithms "IS-LUCB,Pull m,MCCFR OS (eps = 0.1),IS-UCB,On Path (balanced),On Path (uniform)" --yaxisupper 0.1

# python3 plot_graph.py --game "Reconnaissance Blind Tic Tac Toe" --player o --numexperiments 20 --numiterations 990000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_o_C=16_LUCB_exploitability_log,data/MCCFR/eps_constant=0.100000_omccfr_exploitability_log,data/MCCFR/eps_constant=0.100000_omccfr_greedy_exploitability_log,data/bandit/final_exp_o_C=16_UCB_exploitability_log,data/onpath_flipping/eps_constant=0.100000_oonpath_flipping_exploitability_log,data/upfront/eps_constant=0.100000_oupfront_flipping_exploitability_log,data/onpath_balanced/eps_constant=0.100000_oonpath_flipping_exploitability_log,data/upfront_balanced/eps_constant=0.100000_oupfront_flipping_exploitability_log,data/uct/C=5_ouct_exploitability_log,data/smooth_uct/d=0_eps=0.100000_C=3_n0=0.900000ouct_smooth_exploitability_log" --algorithms "IS-LUCB,MCCFR OS (eps = 0.1),MCCFR Eps-Greedy (eps = 0.1),IS-UCB,On Path (uniform),Up Front Flipping (uniform), On Path (balanced),Up Front Flipping (balanced),UCT,Smooth UCT" --yaxisupper 0.5
# python3 plot_graph.py --game "Reconnaissance Blind Tic Tac Toe" --player x --numexperiments 20 --numiterations 990000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_x_C=16_LUCB_exploitability_log,data/MCCFR/eps_constant=0.100000_xmccfr_exploitability_log,data/MCCFR/eps_constant=0.100000_xmccfr_greedy_exploitability_log,data/onpath_flipping/eps_constant=0.100000_xonpath_flipping_exploitability_log,data/upfront/eps_constant=0.100000_xupfront_flipping_exploitability_log,data/onpath_balanced/eps_constant=0.100000_xonpath_flipping_exploitability_log,data/upfront_balanced/eps_constant=0.100000_xupfront_flipping_exploitability_log,data/uct/C=5_ouct_exploitability_log,data/smooth_uct/d=0_eps=0.100000_C=3_n0=0.900000xuct_smooth_exploitability_log" --algorithms "IS-LUCB,MCCFR OS (eps = 0.1),MCCFR Eps-Greedy (eps = 0.1),On Path (uniform),Up Front Flipping (uniform),On Path (balanced),Up Front Flipping (balanced),UCT,Smooth UCT" --yaxisupper 0.5

# start policy for RBT
python3 plot_graph.py --game "RBT, Start Policy" --player x --numexperiments 20 --numiterations 990000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/start_policy_x_C=16_LUCB_exploitability_log,data/MCCFR/start_policy_eps_constant=0.100000_xmccfr_exploitability_log" --algorithms "IS-LUCB,MCCFR OS (eps = 0.1)" --yaxisupper 0.5

# Paper Specific Plots
python3 plot_graph.py --game "Kuhn Poker, Comparison" --player o --numexperiments 100 --numiterations 10000 --logfreq 100 --cours 16 --logfiles "data/bandit/comparison_K_poker_o_C=16_IS-LUCB_exploitability_log,data/exact/comparison_Kuhn_Poker_exact_LUCB_o_run,data/exact/comparisonKuhn_Poker_exact_LUCB_update_all_o_run" --algorithms "IS-LUCB,Exact LUCB (Update 1),Exact LUCB (Update All)" --yaxisupper 0.2
python3 plot_graph.py --game "Kuhn Poker, Comparison" --player x --numexperiments 100 --numiterations 10000 --logfreq 100 --cours 16 --logfiles "data/bandit/comparison_K_poker_x_C=16_IS-LUCB_exploitability_log,data/exact/comparison_Kuhn_Poker_exact_LUCB_x_run,data/exact/comparisonKuhn_Poker_exact_LUCB_update_all_x_run" --algorithms "IS-LUCB,Exact LUCB (Update 1),Exact LUCB (Update All)" --yaxisupper 0.2

# python3 plot_graph.py --game "Kuhn Poker, PAC, eps = 0.01, delta = 0.01" --player o --numexperiments 5 --numiterations 100000 --logfreq 10 --logfiles "data/exact/PACKuhn_Poker_exact_LUCB_update_all_o_run" --algorithms "Exact LUCB (Update All)" --yaxisupper 0.2
# python3 plot_graph.py --game "Kuhn Poker, PAC, eps = 0.01, delta = 0.01" --player x --numexperiments 5 --numiterations 100000 --logfreq 10 --logfiles "data/exact/PACKuhn_Poker_exact_LUCB_update_all_x_run" --algorithms "Exact LUCB (Update All)" --yaxisupper 0.2

# python3 plot_graph.py --game "Leduc Poker, Variations" --player o --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --logfiles "data/bandit/final_exp_L_poker_o_C=16_LUCB_exploitability_log,data/bandit/final_exp_pull25k_L_poker_o_pullm_exploitability_log,data/bandit/final_exp_L_poker_o_C=16_UCB_exploitability_log" --algorithms "IS-LUCB,Pull m,IS-UCB" --yaxisupper 0.1
# python3 plot_graph.py --game "Leduc Poker, Variations" --player x --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --logfiles "data/bandit/final_exp_L_poker_x_C=16_LUCB_exploitability_log,data/bandit/final_exp_pull25k_L_poker_x_pullm_exploitability_log,data/bandit/final_exp_L_poker_x_C=16_UCB_exploitability_log" --algorithms "IS-LUCB,Pull m,IS-UCB" --yaxisupper 0.1

# python3 plot_graph.py --game "Kuhn Poker, Variations" --player o --numexperiments 20 --numiterations 1000 --logfreq 10 --cours 16 --logfiles "data/bandit/final_exp_K_poker_o_C=16_LUCB_exploitability_log,data/bandit/final_exp_pull250_K_poker_o_pullm_exploitability_log,data/bandit/final_exp_K_poker_o_C=16_UCB_exploitability_log" --algorithms "IS-LUCB,Pull m,IS-UCB" --yaxisupper 0.1
# python3 plot_graph.py --game "Kuhn Poker, Variations" --player x --numexperiments 20 --numiterations 1000 --logfreq 10 --cours 16 --logfiles "data/bandit/final_exp_K_poker_x_C=16_LUCB_exploitability_log,data/bandit/final_exp_pull250_K_poker_x_pullm_exploitability_log,data/bandit/final_exp_K_poker_x_C=16_UCB_exploitability_log" --algorithms "IS-LUCB,Pull m,IS-UCB" --yaxisupper 0.1

# Paper Main Plots
python3 plot_graph.py --game "RBT, Best Algorithms" --player o --numexperiments 20 --numiterations 990000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_o_C=16_LUCB_exploitability_log,data/MCCFR/eps_constant=0.100000_omccfr_exploitability_log,data/onpath_balanced/eps_constant=0.100000_oonpath_flipping_exploitability_log,data/smooth_uct/d=0_eps=0.100000_C=3_n0=0.900000ouct_smooth_exploitability_log" --algorithms "IS-LUCB,MCCFR OS,On Path Flipping,Smooth UCT" --yaxisupper 0.5
python3 plot_graph.py --game "RBT, Best Algorithms" --player x --numexperiments 20 --numiterations 990000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_x_C=16_LUCB_exploitability_log,data/MCCFR/eps_constant=0.100000_xmccfr_exploitability_log,data/onpath_balanced/eps_constant=0.100000_xonpath_flipping_exploitability_log,data/smooth_uct/d=0_eps=0.100000_C=3_n0=0.900000xuct_smooth_exploitability_log" --algorithms "IS-LUCB,MCCFR OS,On Path Flipping,Smooth UCT" --yaxisupper 0.5

python3 plot_graph.py --game "Leduc Poker, Best Algorithms" --player o --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_o_C=16_IS-LUCB_exploitability_log,data/MCCFR/L_poker_o_MCCFR_OS_exploitability_log,data/onpath_flipping/final_exp_L_poker_k=10.000000_oonpath_flipping_exploitability_log,data/smooth_uct/d=0_eps=0.100000_C=2.000000_n0=0.900000o_Lpoker_uct_smooth_exploitability_log,data/uct/C=2.000000_o_Lpoker_uct_exploitability_log,data/sequence/first_run_L_poker_o_C_r=0.350000_C_p=0.350000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,MCCFR OS,On-path Flipping,Smooth UCT,UCT,Sequence LUCB" --yaxisupper 0.15 --plotpath "plots/leduc_poker_o"
python3 plot_graph.py --game "Leduc Poker, Best Algorithms" --player x --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_x_C=16_IS-LUCB_exploitability_log,data/MCCFR/L_poker_x_MCCFR_OS_exploitability_log,data/onpath_flipping/final_exp_L_poker_k=10.000000_xonpath_flipping_exploitability_log,data/smooth_uct/d=0_eps=0.100000_C=2.000000_n0=0.900000x_Lpoker_uct_smooth_exploitability_log,data/uct/C=2.000000_x_Lpoker_uct_exploitability_log,data/sequence/first_run_L_poker_x_C_r=0.350000_C_p=0.350000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,MCCFR OS,On-path Flipping,Smooth UCT,UCT,Sequence LUCB" --yaxisupper 0.15 --plotpath "plots/leduc_poker_x"

python3 plot_graph.py --game "Kuhn Poker, Best Algorithms" --player o --numexperiments 100 --numiterations 1000 --logfreq 10 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_K_poker_o_C=16_IS-LUCB_exploitability_log,data/bandit/IS-LUCB-2_K_poker_o_C=16_IS-LUCB_exploitability_log" --algorithms "IS-LUCB,IS-LUCB-2" --yaxisupper 0.15 --plotpath plot_o.pdf
python3 plot_graph.py --game "Kuhn Poker, Best Algorithms" --player x --numexperiments 100 --numiterations 1000 --logfreq 10 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_K_poker_x_C=16_IS-LUCB_exploitability_log,data/bandit/IS-LUCB-2_K_poker_x_C=16_IS-LUCB_exploitability_log" --algorithms "IS-LUCB,IS-LUCB-2" --yaxisupper 0.15 --plotpath plot_x.pdf

python3 plot_graph.py --game "Leduc Poker, Best Algorithms" --player o --numexperiments 10 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_o_C=16_IS-LUCB_exploitability_log,data/bandit/IS-LUCB-2_L_poker_o_C=16_IS-LUCB_exploitability_log,data/bandit/IS-UCB-2_L_poker_o_C=16_IS-LUCB_exploitability_log" --algorithms "IS-LUCB,IS-LUCB-2,IS-UCB-2" --yaxisupper 0.15 --plotpath plot_o.pdf
python3 plot_graph.py --game "Leduc Poker, Best Algorithms" --player x --numexperiments 10 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_x_C=16_IS-LUCB_exploitability_log,data/bandit/IS-LUCB-2_L_poker_x_C=16_IS-LUCB_exploitability_log,data/bandit/IS-UCB-2_L_poker_x_C=16_IS-LUCB_exploitability_log" --algorithms "IS-LUCB,IS-LUCB-2,IS-UCB-2" --yaxisupper 0.15 --plotpath plot_x.pdf


# RPS
python3 plot_graph.py --game "Rock Paper Scissors" --player x --numexperiments 300 --numiterations 500000 --logfreq 1000 --epsmccfr 0.1 --logfiles "data/RPS/LUCB,data/RPS/xmccfr_exploitability_log,data/RPS/xonpath_exploitability_log" --algorithms "IS-LUCB,MCCFR,On-path Flipping," --yaxisupper 0.01

# data/RPS/OMD
# OMD (g = 0.0047; e = 0.0018)
#  (k = 1)

# KLUCB

# python3 plot_graph.py --game "Leduc Poker, KLUCB" --player o --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --logfiles "data/bandit/final_exp_L_poker_o_C=16_LUCB_exploitability_log,data/bandit/KL_test_L_poker_o_C=0_IS-KLLUCB_exploitability_log,data/bandit/KL_test_L_poker_o_C=3_IS-KLLUCB_exploitability_log,data/bandit/KL_test_L_poker_o_C=16_IS-KLLUCB_exploitability_log" --algorithms "IS-LUCB (C = 16),IS-KLLUCB (C = 0),IS-KLLUCB (C = 3),IS-KLLUCB (C = 16)" --yaxisupper 0.025
# python3 plot_graph.py --game "Leduc Poker, KLUCB" --player x --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --logfiles "data/bandit/final_exp_L_poker_x_C=16_LUCB_exploitability_log,data/bandit/KL_test_L_poker_x_C=0_IS-KLLUCB_exploitability_log,data/bandit/KL_test_L_poker_x_C=3_IS-KLLUCB_exploitability_log,data/bandit/KL_test_L_poker_x_C=16_IS-KLLUCB_exploitability_log" --algorithms "IS-LUCB (C = 16),IS-KLLUCB (C = 0),IS-KLLUCB (C = 3),IS-KLLUCB (C = 16)" --yaxisupper 0.025

# python3 plot_graph.py --game "Kuhn Poker, KLUCB" --player o --numexperiments 20 --numiterations 1000 --logfreq 10 --cours 16 --logfiles "data/bandit/final_exp_K_poker_o_C=16_LUCB_exploitability_log,data/bandit/KL_test_K_poker_o_C=0_IS-KLLUCB_exploitability_log,data/bandit/KL_test_K_poker_o_C=3_IS-KLLUCB_exploitability_log,data/bandit/KL_test_K_poker_o_C=16_IS-KLLUCB_exploitability_log" --algorithms "IS-LUCB (C = 16),IS-KLLUCB (C = 0),IS-KLLUCB (C = 3),IS-KLLUCB (C = 16)" --yaxisupper 0.1
# python3 plot_graph.py --game "Kuhn Poker, KLUCB" --player x --numexperiments 20 --numiterations 1000 --logfreq 10 --cours 16 --logfiles "data/bandit/final_exp_K_poker_x_C=16_LUCB_exploitability_log,data/bandit/KL_test_K_poker_x_C=0_IS-KLLUCB_exploitability_log,data/bandit/KL_test_K_poker_x_C=3_IS-KLLUCB_exploitability_log,data/bandit/KL_test_K_poker_x_C=16_IS-KLLUCB_exploitability_log" --algorithms "IS-LUCB (C = 16),IS-KLLUCB (C = 0),IS-KLLUCB (C = 3),IS-KLLUCB (C = 16)" --yaxisupper 0.1

# Our algorithm vs MDP-GapE
python3 plot_graph.py --game "Leduc Poker, MDP-GapE" --player x --numexperiments 20 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_x_C=16_IS-LUCB_exploitability_log,data/gapE/x_L_gapE_exploitability_log" --algorithms "IS-LUCB,MDP-GapE" --yaxisupper 0.15 --plotpath "plots/leduc_poker_x_gapE"

python3 plot_graph.py --game "Kuhn Poker, MDP-GapE" --player o --numexperiments 100 --numiterations 1000 --logfreq 10 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_K_poker_o_C=16_IS-LUCB_exploitability_log,data/gapE/o_K_gapE_exploitability_log" --algorithms "IS-LUCB,MDP-GapE" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_o_gapE"
python3 plot_graph.py --game "Kuhn Poker, MDP-GapE" --player x --numexperiments 100 --numiterations 1000 --logfreq 10 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_K_poker_x_C=16_IS-LUCB_exploitability_log,data/gapE/x_K_gapE_exploitability_log" --algorithms "IS-LUCB,MDP-GapE" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_x_gapE"

# IS-LUCB vs Thompson Sampling
python3 plot_graph.py --game "Kuhn Poker, Top Two Thompson" --player o --numexperiments 100 --numiterations 1000 --logfreq 10 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_K_poker_o_C=16_IS-LUCB_exploitability_log,data/bandit/test_1203_K_poker_o_top_two_thompson_exploitability_log" --algorithms "IS-LUCB,TTTS" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_o_ttt"
python3 plot_graph.py --game "Kuhn Poker, Top Two Thompson" --player x --numexperiments 100 --numiterations 1000 --logfreq 10 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_K_poker_x_C=16_IS-LUCB_exploitability_log,data/bandit/test_1203_K_poker_x_top_two_thompson_exploitability_log" --algorithms "IS-LUCB,TTTS" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_x_ttt"

python3 plot_graph.py --game "Leduc Poker, Top Two Thompson" --player o --numexperiments 10 --numiterations 100000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_o_C=16_IS-LUCB_exploitability_log,data/bandit/test_1203_L_poker_o_top_two_thompson_exploitability_log" --algorithms "IS-LUCB,Top Two Thompson" --yaxisupper 0.15 --plotpath "plots/leduc_poker_o_ttt"
python3 plot_graph.py --game "Leduc Poker, Top Two Thompson" --player x --numexperiments 10 --numiterations 100000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_L_poker_x_C=16_IS-LUCB_exploitability_log,data/bandit/test_1203_L_poker_x_top_two_thompson_exploitability_log" --algorithms "IS-LUCB,Top Two Thompson" --yaxisupper 0.15 --plotpath "plots/leduc_poker_x_ttt"


# IS-LUCB vs Seq-LUCB
python3 plot_graph.py --game "Kuhn Poker, Sequence LUCB" --player o --numexperiments 100 --numiterations 1000 --logfreq 10 --cours 16 --logfiles "data/bandit/final_exp_K_poker_o_C=16_IS-LUCB_exploitability_log,data/sequence/second_run_K_poker_o_C_r=2.000000_C_p=2.000000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_o_seq"
python3 plot_graph.py --game "Kuhn Poker, Sequence LUCB" --player x --numexperiments 100 --numiterations 1000 --logfreq 10 --cours 16 --logfiles "data/bandit/final_exp_K_poker_x_C=16_IS-LUCB_exploitability_log,data/sequence/second_run_K_poker_x_C_r=2.000000_C_p=2.000000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_x_seq"

python3 plot_graph.py --game "Leduc Poker, Sequence LUCB" --player o --numexperiments 20 --numiterations 1000000 --logfreq 10000 --logfiles "data/bandit/final_exp_L_poker_o_C=16_IS-LUCB_exploitability_log,data/sequence/second_run_L_poker_o_C_r=0.500000_C_p=0.500000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB" --yaxisupper 0.1 --plotpath "plots/leduc_poker_o_seq"
python3 plot_graph.py --game "Leduc Poker, Sequence LUCB" --player x --numexperiments 20 --numiterations 1000000 --logfreq 10000 --logfiles "data/bandit/final_exp_L_poker_x_C=16_IS-LUCB_exploitability_log,data/sequence/second_run_L_poker_x_C_r=0.500000_C_p=0.500000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB" --yaxisupper 0.1 --plotpath "plots/leduc_poker_x_seq"

python3 plot_graph.py --game "RBT, Sequence LUCB" --player o --numexperiments 10 --numiterations 990000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_o_C=16_LUCB_exploitability_log,data/sequence/second_run_rbt_o_C_r=1.000000_C_p=1.000000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB" --yaxisupper 0.5 --plotpath "plots/rbt_o_seq"
python3 plot_graph.py --game "RBT, Sequence LUCB" --player x --numexperiments 5 --numiterations 990000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/bandit/final_exp_x_C=16_LUCB_exploitability_log,data/sequence/second_run_rbt_x_C_r=1.000000_C_p=1.000000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB" --yaxisupper 0.5 --plotpath "plots/rbt_x_seq"

# data/sequence/KL_L_poker_o_C_r=1.000000_C_p=1.000000_seq-LUCB_exploitability_log
# data/sequence/KL_L_poker_x_C_r=1.000000_C_p=1.000000_seq-LUCB_exploitability_log
python3 plot_graph.py --game "Leduc Poker, PAC" --player o --numexperiments 50 --numiterations 1000000 --logfreq 10000 --logfiles "data/gapE/o_L_BPIUCRL_exploitability_log,data/gapE/o_L_gapE_exploitability_log,data/sequence/AAAI_L_poker_o_C=1.000000_C_r=1.000000_seq-LUCB_exploitability_log,data/sequence/AAAI_test_L_poker_o_C=1.000000_C_r=1.000000_seq-LUCB_exploitability_log" --algorithms "BPI-UCRL,MDP-GapE,LUCBT,LUCBT(fixed)" --yaxisupper 0.025 --plotpath "plots/leduc_poker_o_AAAI_PAC"
python3 plot_graph.py --game "Leduc Poker, PAC" --player x --numexperiments 50 --numiterations 1000000 --logfreq 10000 --logfiles "data/gapE/x_L_BPIUCRL_exploitability_log,data/gapE/x_L_gapE_exploitability_log,data/sequence/AAAI_L_poker_x_C=1.000000_C_r=1.000000_seq-LUCB_exploitability_log,data/sequence/AAAI_test_L_poker_x_C=1.000000_C_r=1.000000_seq-LUCB_exploitability_log" --algorithms "BPI-UCRL,MDP-GapE,LUCBT,LUCBT(fixed)" --yaxisupper 0.025 --plotpath "plots/leduc_poker_x_AAAI_PAC"

python3 plot_graph.py --game "Kuhn Poker, PAC" --player o --numexperiments 100 --numiterations 1000 --logfreq 10 --logfiles "data/gapE/o_K_BPIUCRL_exploitability_log,data/gapE/o_K_gapE_exploitability_log,data/sequence/AAAI_K_poker_o_C=0.050000_C_r=0.050000_seq-LUCB_exploitability_log,data/sequence/AAAI_test_K_poker_o_C=0.050000_C_r=0.050000_seq-LUCB_exploitability_log" --algorithms "BPI-UCRL,MDP-GapE,LUCBT,LUCBT(fixed)" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_o_AAAI_PAC"
python3 plot_graph.py --game "Kuhn Poker, PAC" --player x --numexperiments 100 --numiterations 1000 --logfreq 10 --logfiles "data/gapE/x_K_BPIUCRL_exploitability_log,data/gapE/x_K_gapE_exploitability_log,data/sequence/AAAI_K_poker_x_C=0.050000_C_r=0.050000_seq-LUCB_exploitability_log,data/sequence/AAAI_test_K_poker_x_C=0.050000_C_r=0.050000_seq-LUCB_exploitability_log" --algorithms "BPI-UCRL,MDP-GapE,LUCBT,LUCBT(fixed)" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_x_AAAI_PAC"

python3 plot_graph.py --game "Kuhn Poker, Sequence LUCB" --player o --numexperiments 100 --numiterations 1000 --logfreq 10 --logfiles "data/bandit/final_exp_K_poker_o_C=16_IS-LUCB_exploitability_log,data/sequence/third_run_K_poker_o_C_r=2.000000_C_p=2.000000_seq-LUCB_exploitability_log,data/sequence/KL_K_poker_o_C_r=1.000000_C_p=1.000000_seq-LUCB_exploitability_log,data/sequence/deterministic_K_poker_o_C=0.100000_C_r=0.100000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB,Sequence LUCB (KL),Sequence LUCB (2)" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_o_two_step"
python3 plot_graph.py --game "Kuhn Poker, Sequence LUCB" --player x --numexperiments 100 --numiterations 1000 --logfreq 10 --logfiles "data/bandit/final_exp_K_poker_x_C=16_IS-LUCB_exploitability_log,data/sequence/third_run_K_poker_x_C_r=2.000000_C_p=2.000000_seq-LUCB_exploitability_log,data/sequence/KL_K_poker_x_C_r=1.000000_C_p=1.000000_seq-LUCB_exploitability_log,data/sequence/deterministic_K_poker_x_C=0.100000_C_r=0.100000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB,Sequence LUCB (KL),Sequence LUCB (2)" --yaxisupper 0.15 --plotpath "plots/kuhn_poker_x_two_step"

python3 plot_graph.py --game "RBT, Sequence LUCB" --player o --numexperiments 4 --numiterations 990000 --logfreq 10000 --cours 16 --logfiles "data/bandit/final_exp_o_C=16_LUCB_exploitability_log,data/sequence/KL_rbt_o_C_r=4.000000_C_p=4.000000_seq-LUCB_exploitability_log,data/sequence/new_implementation_rbt_o_C=1.000000_C_r=1.000000_seq-LUCB_exploitability_log,data/sequence/regret_rbt_o_C=1.000000_C_r=1.000000_seq-UCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB (KL),LUCBT,UCBT" --yaxisupper 0.5 --plotpath "plots/rbt_o_sequence"
python3 plot_graph.py --game "RBT, Sequence LUCB" --player x --numexperiments 10 --numiterations 990000 --logfreq 10000 --cours 16 --logfiles "data/bandit/final_exp_x_C=16_LUCB_exploitability_log,data/sequence/KL_rbt_x_C_r=4.000000_C_p=4.000000_seq-LUCB_exploitability_log,data/sequence/new_implementation_rbt_x_C=1.000000_C_r=1.000000_seq-LUCB_exploitability_log,data/sequence/random_rbt_x_C=0.100000_C_r=0.100000_seq-LUCB_exploitability_log" --algorithms "IS-LUCB,Sequence LUCB (KL),LUCBT" --yaxisupper 0.5 --plotpath "plots/rbt_x_sequence"

python3 plot_graph.py --game "Sequence LUCB" --player x --numexperiments 40 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/sequence/KL_rbt_x_C_r=4.000000_C_p=4.000000_seq-LUCB_exploitability_log" --algorithms "Sequence LUCB" --yaxisupper 0.5 --plotpath "plots/rbt_x_two_step_only"
python3 plot_graph.py --game "Sequence LUCB" --player o --numexperiments 40 --numiterations 1000000 --logfreq 10000 --cours 16 --epsmccfr 0.1 --logfiles "data/sequence/KL_rbt_o_C_r=4.000000_C_p=4.000000_seq-LUCB_exploitability_log" --algorithms "Sequence LUCB" --yaxisupper 0.5 --plotpath "plots/rbt_o_two_step_only"

python3 plot_graph.py --game "RBT, Sequence LUCB" --player x --numexperiments 5 --numiterations 2000000 --logfreq 10000 --logfiles "data/sequence/minmethod_rbt_x_C=0.100000_C_r=0.100000_seq-LUCB_exploitability_log" --algorithms "Sequence LUCB (2)" --yaxisupper 0.5 --plotpath "plots/rbt_x_sequence_long"

# regret plots

python3 plot_graph.py --game "Leduc Poker, Sequence LUCB" --player x --numexperiments 20 --numiterations 10000 --logfreq 100 --logfiles "data/sequence/10k_L_poker_x_C=2.000000_C_r=8.000000_seq-UCB_reward_log,data/sequence/10k_L_poker_x_C=2.000000_C_r=8.000000_seq-LUCB_reward_log" --algorithms "UCBT,LUCBT" --yaxisupper 0.05 --plotpath "plots/leduc_poker_regret_x_AAAI" --regret 1
python3 plot_graph.py --game "RBT, Sequence LUCB" --player o --numexperiments 10 --numiterations 100000 --logfreq 1000 --cours 16 --logfiles "data/sequence/10k_rbt_o_C=1.000000_C_r=1.000000_seq-LUCB_reward_log,data/sequence/10k_rbt_o_C=1.000000_C_r=1.000000_seq-UCB_reward_log,data/mccfr/o_reward_mccfr" --algorithms "LUCBT,UCBT,MCCFR(OS)" --yaxisupper 1 --plotpath "plots/rbt_regret_o_AAAI" --regret 1
python3 plot_graph.py --game "RBT, Sequence LUCB" --player x --numexperiments 10 --numiterations 100000 --logfreq 1000 --cours 16 --logfiles "data/sequence/10k_rbt_x_C=1.000000_C_r=1.000000_seq-LUCB_reward_log,data/sequence/10k_rbt_x_C=1.000000_C_r=1.000000_seq-UCB_reward_log,data/mccfr/x_reward_mccfr" --algorithms "LUCBT,UCBT,MCCFR(OS)" --yaxisupper 1 --plotpath "plots/rbt_regret_x_AAAI" --regret 1